-- MySQL Script generated by MySQL Workbench
-- 03/08/16 12:15:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8 ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`category` (
  `id` MEDIUMTEXT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`dish` (
  `id` MEDIUMTEXT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `description` TEXT NOT NULL,
  `ingredients` VARCHAR(80) NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL,
  `image` VARCHAR(50) NOT NULL,
  `category_id` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_dish_category_idx` (`category_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_dish_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `restaurant`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`user` (
  `id` MEDIUMTEXT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `pay_card` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`user_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`user_order` (
  `id` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `total` DECIMAL(12,2) NOT NULL,
  `user_id` MEDIUMTEXT NOT NULL,
  `paid` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `restaurant`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`order_dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`order_dish` (
  `id` MEDIUMTEXT NOT NULL,
  `quantity` INT NOT NULL,
  `dish_id` MEDIUMTEXT NOT NULL,
  `order_id` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`, `dish_id`, `order_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_order_dish_dish1_idx` (`dish_id` ASC),
  INDEX `fk_order_dish_user_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_dish_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `restaurant`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_dish_user_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `restaurant`.`user_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`news` (
  `id` MEDIUMTEXT NOT NULL,
  `content` TEXT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `image` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `restaurant`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `restaurant`;
INSERT INTO `restaurant`.`category` (`id`, `name`, `description`) VALUES ('1', 'Drinks', 'Different drinks');
INSERT INTO `restaurant`.`category` (`id`, `name`, `description`) VALUES ('2', 'Appetizers', 'Served before main course');
INSERT INTO `restaurant`.`category` (`id`, `name`, `description`) VALUES ('3', 'Soups', 'Boiled mixed products');
INSERT INTO `restaurant`.`category` (`id`, `name`, `description`) VALUES ('4', 'Salads', 'Mixed vegetables with sauce');
INSERT INTO `restaurant`.`category` (`id`, `name`, `description`) VALUES ('5', 'Desserts', 'Sweet food');
INSERT INTO `restaurant`.`category` (`id`, `name`, `description`) VALUES ('6', 'Sides', 'Added to meat');

COMMIT;


-- -----------------------------------------------------
-- Data for table `restaurant`.`dish`
-- -----------------------------------------------------
START TRANSACTION;
USE `restaurant`;
INSERT INTO `restaurant`.`dish` (`id`, `name`, `description`, `ingredients`, `price`, `quantity`, `image`, `category_id`) VALUES ('1', 'MySoup1', 'hot cool soup', 'water and colt', 10.00, 20, 'soup.png', '3');
INSERT INTO `restaurant`.`dish` (`id`, `name`, `description`, `ingredients`, `price`, `quantity`, `image`, `category_id`) VALUES ('2', 'MySoup2', 'hot cool soup', 'water and colt', 10.00, 20, 'soup.png', '3');
INSERT INTO `restaurant`.`dish` (`id`, `name`, `description`, `ingredients`, `price`, `quantity`, `image`, `category_id`) VALUES ('3', 'MySoup3', 'hot cool soup', 'water and colt', 10.00, 20, 'soup.png', '3');
INSERT INTO `restaurant`.`dish` (`id`, `name`, `description`, `ingredients`, `price`, `quantity`, `image`, `category_id`) VALUES ('4', 'Apple Juice', 'drink from soup', 'apples', 2.50, 20, 'applejuice.png', '1');
INSERT INTO `restaurant`.`dish` (`id`, `name`, `description`, `ingredients`, `price`, `quantity`, `image`, `category_id`) VALUES ('5', 'Orange Juice', 'drink from soup', 'oranges', 2.50, 20, 'orangejuice.png', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `restaurant`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `restaurant`;
INSERT INTO `restaurant`.`user` (`id`, `name`, `surname`, `login`, `password`, `email`, `role`, `pay_card`) VALUES ('1', 'vera', 'chigir', 'vera', '123', 'vera@mail.ru', 'ADMIN', '1');
INSERT INTO `restaurant`.`user` (`id`, `name`, `surname`, `login`, `password`, `email`, `role`, `pay_card`) VALUES ('2', 'Иван', 'Иванов', 'иван', '123', 'ivan@mail.ru', 'USER', '2');
INSERT INTO `restaurant`.`user` (`id`, `name`, `surname`, `login`, `password`, `email`, `role`, `pay_card`) VALUES ('3', 'Peter', 'Petrov', 'peter', '123', 'peter@mail.ru', 'USER', '3');
INSERT INTO `restaurant`.`user` (`id`, `name`, `surname`, `login`, `password`, `email`, `role`, `pay_card`) VALUES ('4', 'Jonh', 'Smith', 'john', '123', 'john@mail.ru', 'USER', '4');
INSERT INTO `restaurant`.`user` (`id`, `name`, `surname`, `login`, `password`, `email`, `role`, `pay_card`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '', DEFAULT, DEFAULT, DEFAULT);

COMMIT;

